// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt94sxN3GbLX4yZptV0BViWjL9kZhSHwM',
    appId: '1:191385216323:web:be8f4f06046aded99d7bf6',
    messagingSenderId: '191385216323',
    projectId: 'pinlend-de45e',
    authDomain: 'pinlend-de45e.firebaseapp.com',
    storageBucket: 'pinlend-de45e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOh2384-vQC0_WSygiqov2PEyXkeKETI',
    appId: '1:191385216323:android:2efef1af52d50bf19d7bf6',
    messagingSenderId: '191385216323',
    projectId: 'pinlend-de45e',
    storageBucket: 'pinlend-de45e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4TGYYtMIUjpD03M3I7akzsk096VkStEg',
    appId: '1:191385216323:ios:cf2ef5306126fdab9d7bf6',
    messagingSenderId: '191385216323',
    projectId: 'pinlend-de45e',
    storageBucket: 'pinlend-de45e.firebasestorage.app',
    iosBundleId: 'com.lend.ro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4TGYYtMIUjpD03M3I7akzsk096VkStEg',
    appId: '1:191385216323:ios:a2a0d210f993466c9d7bf6',
    messagingSenderId: '191385216323',
    projectId: 'pinlend-de45e',
    storageBucket: 'pinlend-de45e.firebasestorage.app',
    iosBundleId: 'com.example.lend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt94sxN3GbLX4yZptV0BViWjL9kZhSHwM',
    appId: '1:191385216323:web:d931ed542f0bbe659d7bf6',
    messagingSenderId: '191385216323',
    projectId: 'pinlend-de45e',
    authDomain: 'pinlend-de45e.firebaseapp.com',
    storageBucket: 'pinlend-de45e.firebasestorage.app',
  );
}
